/**
 * Attach note to Google Calendar event
 * Adds note content to the calendar event description
 */

import { NextRequest, NextResponse } from 'next/server';
import { withAuth } from '@/lib/auth-middleware';
import { adminDb } from '@/lib/firebase-admin';
import { attachNoteToCalendarEvent } from '@/lib/google-calendar';
import { Note } from '@/types';

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  return withAuth(request, async (req, user) => {
    try {
      const { id } = await params;
      
      // Get the note
      const noteRef = adminDb.collection('notes').doc(id);
      const noteDoc = await noteRef.get();
      
      if (!noteDoc.exists) {
        return NextResponse.json(
          { error: 'Note not found' },
          { status: 404 }
        );
      }
      
      const noteData = noteDoc.data() as Note;
      
      // Check if user owns this note
      if (noteData.createdBy !== user.uid) {
        return NextResponse.json(
          { error: 'Access denied' },
          { status: 403 }
        );
      }
      
      // Check if note is linked to a calendar event
      if (!noteData.calendarEventId) {
        return NextResponse.json(
          { error: 'Note is not linked to a calendar event' },
          { status: 400 }
        );
      }
      
      // Format note content for calendar
      const formattedContent = formatNoteForCalendar(noteData);
      
      // Attach to calendar event (creates Drive file and links it)
      await attachNoteToCalendarEvent(user.uid, noteData.calendarEventId, noteData.title, formattedContent);
      
      return NextResponse.json({
        success: true,
        message: 'Note attached to calendar event',
      });
    } catch (error) {
      console.error('Error attaching note to calendar:', error);
      return NextResponse.json(
        { error: 'Failed to attach note to calendar' },
        { status: 500 }
      );
    }
  });
}

/**
 * Format note content for calendar event description (HTML format for Google Suite compatibility)
 */
function formatNoteForCalendar(note: Note): string {
  let html = `<h1>${note.title}</h1>\n`;
  html += `<p><em>Created: ${new Date(note.createdAt).toLocaleString('de-DE', { timeZone: 'Europe/Berlin' })}</em></p>\n`;
  html += `<hr>\n\n`;
  
  // Add each section
  for (const [sectionId, content] of Object.entries(note.content)) {
    if (content.trim()) {
      // Find section title from template
      const sectionTitle = sectionId
        .split('-')
        .map(word => word.charAt(0).toUpperCase() + word.slice(1))
        .join(' ');
      
      html += `<h2>${sectionTitle}</h2>\n`;
      html += `<div>${content}</div>\n\n`;
    }
  }
  
  // Add tasks section
  if (note.tasks.length > 0) {
    html += `<h2>Tasks</h2>\n`;
    html += `<ul>\n`;
    note.tasks.forEach((task) => {
      const deadline = task.deadline ? ` <em>(Due: ${new Date(task.deadline).toLocaleDateString('de-DE')})</em>` : '';
      const status = task.createdTaskId ? ' ✓' : '';
      html += `<li><strong>${task.title}</strong> - ${task.owner}${deadline}${status}</li>\n`;
    });
    html += `</ul>\n`;
  }
  
  html += `<hr>\n`;
  html += `<p><small>Generated by HelloFresh Task Manager</small></p>`;
  
  return html;
}
